### ISSUE TITLE
Add TypeScript types for country-data-list

### ISSUE THREAD

**Issue by rmiyazaki6499** [Sonatrix/country-list#16]
As a developer using country-data-list, I find it inconvenient that the library's data is currently untyped. This makes it harder to integrate country-data-list with my codebase, which is typed, and can cause errors that are difficult to catch.

I would like to request the addition of TypeScript definitions for country-data-list to make it easier to use with other typed libraries and tools. This would involve adding types to the existing index.d.ts file or creating a new file specifically for the types.

**Comment by rmiyazaki6499** [comment]
Just to add, it can probably be done fairly easily with tools such as Quicktype (https://quicktype.io/typescript) or MakeTypes (https://jvilk.com/MakeTypes/)

**Comment by Sonatrix** [comment]
@rmiyazaki6499 , I have added typescript definitions

**Comment by rmiyazaki6499** [comment]
Awesome! Thank you so much @Sonatrix !
I appreciate the work and have been enjoying working with your library
