### ISSUE TITLE
Emoji Not loading

### ISSUE THREAD

**Issue by sayami007** [Sonatrix/country-list#6]
Hi there, 
I tried loading the country flag using emoji object, but it is not loaded. Should I add any there dependencies for it?
The image was working earlier though.

![image](https://user-images.githubusercontent.com/12579109/122264228-04573480-cef7-11eb-92ad-0c26f9f4ed32.png)

**Comment by Sonatrix** [comment]
Hi @sayami007 , could you please check what change has affected this? This module only provides data list not UI dependencies.
May be one of the npm package has affected this. Please verify the changes you have done from the last change It worked.
You can also downgrade the package and check it's working or not.

**Comment by sayami007** [comment]
@Sonatrix , hey, I found out that it is working on Firefox but not in the chromium-based browser :(


If anyone is facing the same issue, you can import the emoji css.

https://emoji-css.afeld.me/

**Comment by Sonatrix** [comment]
@sayami007 I think its browser issue. check browser compatibility css
